export const prefectures = [
  { header: '北海道・東北地方' },
  { name: '北海道', value: '北海道' },
  { name: '青森県', value: '青森県' },
  { name: '岩手県', value: '岩手県' },
  { name: '宮城県', value: '宮城県' },
  { name: '秋田県', value: '秋田県' },
  { name: '山形県', value: '山形県' },
  { name: '福島県', value: '福島県' },
  { divider: true },
  { header: '関東地方' },
  { name: '茨城県', value: '茨城県' },
  { name: '栃木県', value: '栃木県' },
  { name: '群馬県', value: '群馬県' },
  { name: '埼玉県', value: '埼玉県' },
  { name: '千葉県', value: '千葉県' },
  { name: '東京都', value: '東京都' },
  { name: '神奈川県', value: '神奈川県' },
  { divider: true },
  { header: '中部地方' },
  { name: '新潟県', value: '新潟県' },
  { name: '富山県', value: '富山県' },
  { name: '石川県', value: '石川県' },
  { name: '福井県', value: '福井県' },
  { name: '山梨県', value: '山梨県' },
  { name: '長野県', value: '長野県' },
  { name: '岐阜県', value: '岐阜県' },
  { name: '静岡県', value: '静岡県' },
  { name: '愛知県', value: '愛知県' },
  { divider: true },
  { header: '近畿地方' },
  { name: '三重県', value: '三重県' },
  { name: '滋賀県', value: '滋賀県' },
  { name: '京都府', value: '京都府' },
  { name: '大阪府', value: '大阪府' },
  { name: '兵庫県', value: '兵庫県' },
  { name: '奈良県', value: '奈良県' },
  { name: '和歌山県', value: '和歌山県' },
  { divider: true },
  { header: '中国地方' },
  { name: '鳥取県', value: '鳥取県' },
  { name: '島根県', value: '島根県' },
  { name: '岡山県', value: '岡山県' },
  { name: '広島県', value: '広島県' },
  { name: '山口県', value: '山口県' },
  { divider: true },
  { header: '四国地方' },
  { name: '徳島県', value: '徳島県' },
  { name: '香川県', value: '香川県' },
  { name: '愛媛県', value: '愛媛県' },
  { name: '高知県', value: '高知県' },
  { divider: true },
  { header: '九州地方' },
  { name: '福岡県', value: '福岡県' },
  { name: '佐賀県', value: '佐賀県' },
  { name: '長崎県', value: '長崎県' },
  { name: '熊本県', value: '熊本県' },
  { name: '大分県', value: '大分県' },
  { name: '宮崎県', value: '宮崎県' },
  { name: '鹿児島県', value: '鹿児島県' },
  { name: '沖縄県', value: '沖縄県' },
  { divider: true },
  { header: 'その他' },
  { name: '不明' }
]

export const genders = [
  { name: '男性', value: '男性' },
  { name: '女性', value: '女性' },
  { name: '不明', value: '不明' }
]

export const ages = [
  { name: '10歳未満', value: '0-10' },
  { name: '10代', value: '10' },
  { name: '20代', value: '20' },
  { name: '30代', value: '30' },
  { name: '40代', value: '40' },
  { name: '50代', value: '50' },
  { name: '60代', value: '60' },
  { name: '70代', value: '70' },
  { name: '80代', value: '80' },
  { name: '90代', value: '90' },
  { name: '100代', value: '100' },
  { name: '110代', value: '110' },
  { name: '不明', value: '不明' }
]
