name: pull-req-preview

on:
  pull_request:
    branches:
      - staging

jobs:
  pull-req-preview:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - run: yarn install --frozen-lockfile
      - run: yarn run download-data
      - run: yarn run test
      - run: yarn run generate:dev --fail-on-page-error
        env:
          GOOGLE_ANALYTICS_ID: ${{ secrets.STAGING_GOOGLE_ANALYTICS_ID }}
      - run: "echo \"User-agent: *\nDisallow: /\" > ./dist/robots.txt"

      - name: checkout branch for publish
        run: git checkout -b pull-req-preview-public

      - name: Commit files
        run: |
          echo ${{ github.ref }}
          git add dist
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "ci: Automated build push" | exit 0
      - name: push
        run: git push "https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git" --follow-tags -f | exit 0

      - name: notify to slack
        uses: mm0202/action_slack-notify@master
        if: always()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
